#!/usr/bin/env bun
/**
 * Installs the native messaging host manifest for every Chrome-family browser
 * it can find.
 *
 * Chrome refuses to talk to a native host unless a manifest naming the
 * extension id sits in the browser's own NativeMessagingHosts directory. One
 * per browser, because profiles and browsers do not share that path.
 *
 * Idempotent: rerun it after moving the repo.
 */

import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";

const HOST_NAME = "sh.dunkirk.prickly";
const EXTENSION_ID = "fokpacegneepaffhbphkadjgljingnbp";

// import.meta.path is already an absolute filesystem path; scripts/ -> repo root.
const ROOT = resolve(dirname(import.meta.path), "..");
const LAUNCHER = join(ROOT, "host/bin/prickly-native-host");
const ENTRY = join(ROOT, "host/bin/prickly.ts");

/**
 * Browser name -> the directory that holds NativeMessagingHosts, relative to
 * ~/Library/Application Support. Chromium forks all keep their own.
 */
const BROWSERS: [label: string, dir: string][] = [
  ["Google Chrome", "Google/Chrome"],
  ["Chrome Beta", "Google/Chrome Beta"],
  ["Chrome Canary", "Google/Chrome Canary"],
  ["Chromium", "Chromium"],
  // Dia and Arc keep the Chromium user-data-dir one level down, and that is
  // where they look for NativeMessagingHosts (confirmed against a working
  // third-party host in Dia/User Data/NativeMessagingHosts).
  ["Dia", "Dia/User Data"],
  ["Arc", "Arc/User Data"],
  ["Brave", "BraveSoftware/Brave-Browser"],
  ["Edge", "Microsoft Edge"],
  ["Vivaldi", "Vivaldi"],
  ["Opera", "Opera Software/Opera Stable"],
];

const home = homedir();

function platform(): "darwin" | "linux" | "windows" | "other" {
  if (process.platform === "darwin") return "darwin";
  if (process.platform === "linux") return "linux";
  if (process.platform === "win32") return "windows";
  return "other";
}

function manifestDir(label: string, dir: string): string | null {
  const os = platform();
  if (os === "darwin") return join(home, "Library/Application Support", dir, "NativeMessagingHosts");
  if (os === "linux") {
    // XDG_CONFIG_HOME is respected by every Chromium fork on Linux.
    const config = process.env.XDG_CONFIG_HOME ?? join(home, ".config");
    const lower = dir.toLowerCase().replace(/\s+/g, "");
    return join(config, lower, "NativeMessagingHosts");
  }
  // Windows reads the registry, which is out of scope for a Bun script; the
  // manifest path is still written so a packaging step can pick it up.
  void label;
  return join(home, "AppData/Local", dir, "NativeMessagingHosts");
}

function bunPath(): string {
  const explicit = process.env.PRICKLY_BUN;
  if (explicit) return explicit;
  // Chrome launches the host with a minimal environment, so an absolute path
  // matters; `bun` alone would not resolve.
  for (const candidate of [process.execPath, "/opt/homebrew/bin/bun", "/usr/local/bin/bun"]) {
    if (candidate && existsSync(candidate) && !candidate.endsWith("prickly.ts")) return candidate;
  }
  return "bun";
}

function writeLauncher(): void {
  const bun = bunPath();
  const body = [
    "#!/bin/sh",
    "# Generated by scripts/install-host.ts. Chrome runs this as the native host.",
    `exec "${bun}" run "${ENTRY}" native-host "$@"`,
    "",
  ].join("\n");
  mkdirSync(dirname(LAUNCHER), { recursive: true });
  writeFileSync(LAUNCHER, body, { mode: 0o755 });
  chmodSync(LAUNCHER, 0o755);
}

function main(): void {
  if (!existsSync(ENTRY)) {
    console.error(`cannot find ${ENTRY}; run this from the repo`);
    process.exit(1);
  }
  writeLauncher();
  console.log(`launcher  ${LAUNCHER}`);

  const manifest = {
    name: HOST_NAME,
    description: "Prickly browser control bridge",
    path: LAUNCHER,
    type: "stdio",
    allowed_origins: [`chrome-extension://${EXTENSION_ID}/`],
  };
  const body = `${JSON.stringify(manifest, null, 2)}\n`;

  const force = process.argv.includes("--all");
  const onlyIdx = process.argv.indexOf("--only");
  const only = onlyIdx === -1 ? null : (process.argv[onlyIdx + 1] ?? "").toLowerCase();
  let installed = 0;
  let skipped = 0;

  for (const [label, dir] of BROWSERS) {
    if (only && !label.toLowerCase().includes(only) && !dir.toLowerCase().includes(only)) {
      continue;
    }
    const target = manifestDir(label, dir);
    if (!target) continue;

    const parentExists = existsSync(dirname(target));
    const alreadyThere = existsSync(join(target, `${HOST_NAME}.json`));
    if (!parentExists && !alreadyThere && !force) {
      skipped++;
      continue;
    }

    mkdirSync(target, { recursive: true });
    const path = join(target, `${HOST_NAME}.json`);
    const previous = existsSync(path) ? readFileSync(path, "utf8") : null;
    writeFileSync(path, body, { mode: 0o644 });
    installed++;
    console.log(`${previous === body ? "=" : "+"} ${label.padEnd(14)} ${path}`);
  }

  console.log("");
  console.log(`installed ${installed}, skipped ${skipped} (browser directory not found)`);
  if (!installed) {
    console.log("nothing to do. Pass --all to write manifests for browsers that are not installed yet.");
    return;
  }
  console.log("");
  console.log("next:");
  console.log("  1. bun run build");
  console.log("  2. load extension/dist as an unpacked extension in each browser");
  console.log(`     (the manifest pins the id, so it will be ${EXTENSION_ID})`);
  console.log("  3. reload the extension, then: bun run host/bin/prickly.ts browsers");
}

main();
